#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "installing"
echo "preparing bash configuration"

rm ~/.bashrc ~/.bash_aliases ~/.bash_env

ln -s $DIR/.bashrc ~/.bashrc

ln -s $DIR/.bash_aliases ~/.bash_aliases

ln -s $DIR/.bash_env ~/.bash_env

# Add git auto-complete
mkdir $DIR/utils ~/utils

curl -L https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash  -o ~/utils/bash-completion.bash
chmod +x ~/utils/bash-completion.bash
echo 'source ~/utils/bash-completion.bash'  >> ~/.bashrc

echo "export PATH=$PATH:$DIR/bin" >> ~/.bash_env
echo "bash configuration done"

echo "installing Node.js"
# Install nodeJs and npm
curl -sL https://deb.nodesource.com/setup_12.x | sudo -E bash -
apt-get update
apt-get install nodejs
node -v
npm -v
echo "done"

echo "installing Chrome"
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
apt install ./google-chrome-stable_current_amd64.deb

echo "done"
exit 0
